CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    isMute BOOLEAN
);

CREATE TABLE Phrases (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL UNIQUE,
    phrase VARCHAR(255) NOT NULL UNIQUE,
    response VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL
);